### ISSUE TITLE
Bug: Palomad starts with updated genesis, but blocks are not being created. No errors in logs, but no blocks

### ISSUE THREAD

**Issue by taariq** [palomachain/paloma#796]
# What is happening?
<details>
  <summary>Section description</summary>
<i>Provide as much context as you can. Give as much context as you can to make it easier for the developers to figure what is happening.</i>
</details>

Upgraded genesis with requirements for Cosmos-SDK v0.47.1 is read by palomad, but validators in genesis are not recognized and blocks are not created. 

curl -S localhost:26657/status | json_pp returns the following:

```
 % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   811  100   811    0     0    98k      0 --:--:-- --:--:-- --:--:--   98k
{
   "id" : -1,
   "jsonrpc" : "2.0",
   "result" : {
      "node_info" : {
         "channels" : "40202122233038606100",
         "id" : "b41cb52b7d024ee7fd237350bf3ebdd63c5c5762",
         "listen_addr" : "45.33.42.146:26656",
         "moniker" : "birdlady",
         "network" : "turtle-dove-net",
         "other" : {
            "rpc_address" : "tcp://0.0.0.0:26657",
            "tx_index" : "on"
         },
         "protocol_version" : {
            "app" : "0",
            "block" : "11",
            "p2p" : "8"
         },
         "version" : "0.37.0"
      },
      "sync_info" : {
         "catching_up" : false,
         "earliest_app_hash" : "",
         "earliest_block_hash" : "",
         "earliest_block_height" : "0",
         "earliest_block_time" : "1970-01-01T00:00:00Z",
         "latest_app_hash" : "",
         "latest_block_hash" : "",
         "latest_block_height" : "0",
         "latest_block_time" : "1970-01-01T00:00:00Z"
      },
      "validator_info" : {
         "address" : "CB031878B4EEB66483B17C723DAA157F477F7159",
         "pub_key" : {
            "type" : "tendermint/PubKeyEd25519",
            "value" : "LaB65QGwVPHNULUQd2CcrHzr1tWzfm7fV/D4+hvKJM8="
         },
         "voting_power" : "0"
      }
   }
}
```
Although the validators are in genesis, we receive no blocks. We believe this issue is genesis related.

Gist of Log output and the addrbook.json
https://gist.github.com/taariq/6b311fffec32790f5ba233ead4e30ef4

# Paloma and pigeon versions and logs
<details>
  <summary>Section description</summary>
<i>Write down paloma version.</i>
<i>Write down pigeon version.</i>
<i>Copy and paste pigeon config file as well as relevant ENV variables.</i>
</details>

Palomad Master and Pigeon Master.

# How to reproduce?
<details>
  <summary>Section description</summary>
  <i>Please write detailed steps of what you were doing for this bug to appear.</i>
</details>

We use the private testnet genesis that was upgraded with Cosmos-SDK v0.47.1 changes to setup here: https://github.com/VolumeFi/paloma-private-testnet/tree/genesis-updates

# What is the expected behaviour?
<details>
  <summary>Section description</summary>
<i>If you know, please write down what is the expected behaviour. If you don't know, that's ok. We can have a discussion in comments.</i>
</details>

Validator keys and validator balances are recognized and blocks are started on the private testnet.

**Comment by taariq** [comment]
Closed with #799

**Comment by verabehr** [comment]
https://gist.github.com/verabehr/deb65d09722412ae926c31790f9a562c logs from latest commit are here

**Comment by verabehr** [comment]
Note that the pubkey in the log line 35 
```
"{"_msg":"This node is not a validator","addr":"CB031878B4EEB66483B17C723DAA157F477F7159","level":"info","module":"consensus","pubKey":"PubKeyEd25519{2DA07AE501B054F1CD50B51077609CAC7CEBD6D5B37E6EDF57F0F8FA1BCA24CF}
```
is different from what shows with the `show validator` command and what is listed in the `priv_validator_key.json`

```
palomad tendermint show-validator
{"@type":"/cosmos.crypto.ed25519.PubKey","key":"LaB65QGwVPHNULUQd2CcrHzr1tWzfm7fV/D4+hvKJM8="}
```
 
``` 
cat priv_validator_key.json
  {
  "address": "CB031878B4EEB66483B17C723DAA157F477F7159",
  "pub_key": {
    "type": "tendermint/PubKeyEd25519",
    "value": "LaB65QGwVPHNULUQd2CcrHzr1tWzfm7fV/D4+hvKJM8="
  },```

**Comment by taariq** [comment]
@0xmuralik, @aleem1314 did you have a chance to test genesis against master? We were able to get rid of "not a validator" errors at consensus start. The keys are validators, but still  not creating blocks. Will you let us know if you're able to identify the issue?

**Comment by aleem1314** [comment]
> @0xmuralik, @aleem1314 did you have a chance to test genesis against master? We were able to get rid of "not a validator" errors at consensus start. The keys are validators, but still not creating blocks. Will you let us know if you're able to identify the issue?

Yeah, tested locally with this [script](https://hackmd.io/@aleem/r1N5FILf3). Upgrade failed with following error

 ```
 failed to load latest version: version of store feeibc mismatch root store's version; expected 69 got 0; new stores should be added using StoreUpgrades
 ```
 
 And to fix above issue, tried upgrade with #797 . This time upgrade went through, after the upgrade all queries returning following error message.
 
 ```
codespace sdk code 18: invalid request: failed to load state at height 75; version does not exist (latest height: 75)
```

**Comment by taariq** [comment]
Merging master into #797. Not sure it will help.

**Comment by taariq** [comment]
@alexanderbez Any thoughts?

**Comment by taariq** [comment]
@aleem1314 okay, looks like this is related https://github.com/cosmos/cosmos-sdk/issues/14620

**Comment by alexanderbez** [comment]
> > @0xmuralik, @aleem1314 did you have a chance to test genesis against master? We were able to get rid of "not a validator" errors at consensus start. The keys are validators, but still not creating blocks. Will you let us know if you're able to identify the issue?
> 
> Yeah, tested locally with this [script](https://hackmd.io/@aleem/r1N5FILf3). Upgrade failed with following error
> 
> ```
> failed to load latest version: version of store feeibc mismatch root store's version; expected 69 got 0; new stores should be added using StoreUpgrades
> ```
> 
> And to fix above issue, tried upgrade with #797 . This time upgrade went through, after the upgrade all queries returning following error message.
> 
> ```
> codespace sdk code 18: invalid request: failed to load state at height 75; version does not exist (latest height: 75)
> ```

All new modules must be stated in the upgrade. E.g.: https://github.com/cosmos/cosmos-sdk/blob/c4489d9785de8b24efe12ba9209669e9dce9e23f/docs/docs/core/15-upgrade.md?plain=1#L88-L98

**Comment by taariq** [comment]
We have started to add new modules here:
https://github.com/palomachain/paloma/pull/797/commits/19ad490a58f4a1542cbd221341d177cfa96ab064#diff-aeec7ddb4cf8b7e9e6e57625770d369cce5f377cc350b42c3aca0427bba8dfbcR153

But...we are missing others?

**Comment by taariq** [comment]
Fixed with #797. We are producing blocks on upgrade.

**Comment by taariq** [comment]
@aleem1314 will you do a final test to re-confirm that you are able to execute GRPC off master branch?

**Comment by aleem1314** [comment]
> @aleem1314 will you do a final test to re-confirm that you are able to execute GRPC off master branch?

I am still getting the same error after the upgrade `  "message": "codespace sdk code 18: invalid request: failed to load state at height 153; version does not exist (latest height: 153)",
`.

**Comment by taariq** [comment]
Closing and moving the codespace error to its own ticket.

**Comment by taariq** [comment]
The codespace SDK issue moved to https://github.com/palomachain/paloma/issues/800

**Comment by aleem1314** [comment]
> What is the gprc command you are running?


`palomad q staking validators` 

or

`curl http://127.0.0.1/cosmos/staking/v1beta1/validators`
